// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Ersetze diese Werte mit deinen eigenen Firebase-Konfigurationen
  // Anleitung: https://firebase.google.com/docs/flutter/setup
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPU-uR_ZLFndfSv1FM1g449i-3y9QByig',
    appId: '1:405004251683:web:9e264742f934d6d24e3796',
    messagingSenderId: '405004251683',
    projectId: 'weltenbibliothek-5d21f',
    authDomain: 'weltenbibliothek-5d21f.firebaseapp.com',
    storageBucket: 'weltenbibliothek-5d21f.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPU-uR_ZLFndfSv1FM1g449i-3y9QByig',
    appId: '1:405004251683:android:9e264742f934d6d24e3796',
    messagingSenderId: '405004251683',
    projectId: 'weltenbibliothek-5d21f',
    storageBucket: 'weltenbibliothek-5d21f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID:ios:YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'weltenbibliothek',
    storageBucket: 'weltenbibliothek.appspot.com',
    iosBundleId: 'com.weltenbibliothek.weltenbibliothek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_APP_ID:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'weltenbibliothek',
    storageBucket: 'weltenbibliothek.appspot.com',
    iosBundleId: 'com.weltenbibliothek.weltenbibliothek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:YOUR_APP_ID:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'weltenbibliothek',
    storageBucket: 'weltenbibliothek.appspot.com',
  );
}
